[workspace]
members = ["mdbook-macro", "use-mdbook", "mdbook-shared", "syntect-html"]

[patch.crates-io]
dioxus = { git = "https://github.com/dioxuslabs/dioxus" }
dioxus-core = { git = "https://github.com/dioxuslabs/dioxus" }
dioxus-core-macro = { git = "https://github.com/dioxuslabs/dioxus" }
dioxus-rsx = { git = "https://github.com/dioxuslabs/dioxus" }
dioxus-router = { git = "https://github.com/dioxuslabs/dioxus" }
