[workspace]
members = ["mdbook-macro", "use-mdbook", "mdbook-shared", "syntect-html"]

[patch.crates-io]
dioxus = { git = "https://github.com/ealmloff/dioxus", branch = "breaking" }
dioxus-core = { git = "https://github.com/ealmloff/dioxus", branch = "breaking" }
dioxus-rsx = { git = "https://github.com/ealmloff/dioxus", branch = "breaking" }
